### ISSUE TITLE
Dexter Model Generation

### ISSUE THREAD

**Issue by tgalery** [dexter/dexter#10]
Hi there, this is a follow up to a previous PR that I submitted to json-wikipedia which added portuguese locale support. It seems that I sucessfully generated the portuguese json version of wikipedia. As far as I understand, one would use that to generate the dexter models. However, I can't find anywhere in the docs how to do so. Is there a command in dexter that is able to do that ?

**Comment by diegoceccarelli** [comment]
Hi @tgalery  have a look to this file: 
https://github.com/dexter/dexter/blob/master/dexter-core/doc/steps-to-use-dexter.txt

ps. we are currently in the process of rewriting the model-generation and other think in order to make the model generation faster and easies to personalize, if you send me your email address I would be happy to share with you the planning document.

**Comment by tgalery** [comment]
Cheers @diegoceccarelli, sorry for missing the docs folder. Rokie mistake. my email is my github nickname @gmail.com.

**Comment by tgalery** [comment]
Just a heads up, after tweaking the config.sh script and running the second script `./scripts/create-label2id-file.sh` I got this:

```
Caused by: it.cnr.isti.hpc.mapdb.MapDBException: file /data/diego/model20130403/mapdb exists but it is not a directory
	at it.cnr.isti.hpc.mapdb.MapDB.openDb(MapDB.java:120)
	at it.cnr.isti.hpc.mapdb.MapDB.<init>(MapDB.java:62)
	at it.cnr.isti.hpc.mapdb.MapDB.getDb(MapDB.java:144)
	at it.cnr.isti.hpc.dexter.label.mapdb.MapDBInstance.getInstance(MapDBInstance.java:42)
	at it.cnr.isti.hpc.dexter.label.mapdb.MapDBLabelToId.<init>(MapDBLabelToId.java:51)
	at it.cnr.isti.hpc.dexter.label.mapdb.MapDBLabelToId.getInstance(MapDBLabelToId.java:59)
	at it.cnr.isti.hpc.dexter.label.IdHelperFactory.getLabelToIdWriter(IdHelperFactory.java:66)
	at it.cnr.isti.hpc.dexter.label.IdHelperFactory.getStdLabelToIdWriter(IdHelperFactory.java:88)
	at it.cnr.isti.hpc.dexter.cli.label.IndexLabelToIdCLI.<clinit>(IndexLabelToIdCLI.java:45)```

it seems that the path are harcoded into the `dexter-conf.xml` file. I subsequently added a `pt` entry there, but it seems that the class reads from the default entry. I might just put a path there and see what happens.

**Comment by tgalery** [comment]
putting an existing path into the default model in `dexter-conf` kind of worked for me. However when I ran `scripts/generate-spots.sh` I got many errors of the form

```
2015-08-13 21:23:49,738 51545 [main] INFO  it.cnr.isti.hpc.dexter.cli.spot.ExtractSpotsCLI - cannot find id for label Jo?o_Carlos_Batista
```

It looks like there's an encoding issue for the titles.

**Comment by diegoceccarelli** [comment]
Yeah you have to change the dexter-conf file with your files. The 'error' that you detect, i think is an error in wikipedia, some that edited the wikitext with a weird encoding, the cli is just telling you that it cannot find an article with that title (look if something similar exists in the dump, it could be also a 'red-link')

**Comment by tgalery** [comment]
Ahh ok then, I just asked that because you mentioned that there could be some problems with logic that reads the uri from the dump (e.g. if the link were `João_Carlos_Batista`, dexter could find an id for it).

**Comment by diegoceccarelli** [comment]
Umm, the problem with the logic could be due to the locale, you should check if ''João_Carlos_Batista'' is a correct wikititle (so if in the json dump there's a record with type ARTICLE, and wikiname =  ''João_Carlos_Batista'' ) if yes, it could be a problem to investigate, or it could be that in that case the wiki-id for ''João_Carlos_Batista'' is misspelled and does not match any wikiname in wikipedia.

**Comment by tgalery** [comment]
Cool, I will check that and give a shout here. If I can't find anything wrong in the dump, I will close this issue.

**Comment by rschwab68** [comment]
I have build the model for german and I too think there is an issue with encoding and internationalization.
I have found one class,  Spot.java, which is using US-ASCII for en/decoding in two methods, toByteArray and fromByteArray.
When I annotate with Dexter, the annotations contains mentions like fur when text mentions für. German Umlaute disappear in the annotations.

**Comment by diegoceccarelli** [comment]
@rschwab68  Yes, that was a design decision for semplifing things. Text is lossy transformed in ascii, so that für becames fur. It simplified the design and improved the recall, since (at least in Italy) people use to write non-ascii words in their ascii format (or they use the wrong letter e.g., è instead of é). Search engines also use the same strategy usually.  

Unfortunately at the moment dexter does not support  utf8. We're working on a new version that will provide this feature, together with impressive indexing and processing speed and other small things :) stay tuned :)

**Comment by TroisLiu** [comment]
Hi, now I'm trying to build the wiki model for the wiki dump - "enwiki-20151201-pages-articles.xml.bz2 "

I have two problem what to ask

1. After I run the create-label2id-file.sh, it create a tsy file : "title-redirect-id.tsv" .
    But I find the file size is zero, and its content is empty. Is that a correct or normal situation?

2.  If the first one is correct, When I run the generate-spots.sh . It show the  exception as below picture:
![dexter-problem-screenshot-20151225](https://cloud.githubusercontent.com/assets/5452974/12002244/a3cf7050-ab34-11e5-9449-4a5d0bdc0e7b.PNG)

I have tried to find the similar problem on stackoverflow or searching on Google, but I still don't have any idea about how to fix it. ~"~

Can you give me some suggestions or solutions? 
Thank you ~

**Comment by diegoceccarelli** [comment]
Hi @TroisLiu, please check that the data folder here: https://github.com/dexter/dexter/blob/master/dexter-core/scripts/config-example.sh#L23 and the one here: https://github.com/dexter/dexter/blob/master/dexter-core/dexter-conf.xml#L8 have the same path, and then restart from the beginning all the steps. I apologize for all these steps, we are going to solve this problem in dexter 3.0 :grinning: 
Let me know if it solved!

**Comment by TroisLiu** [comment]
Hi @diegoceccarelli ,

I have already changed these two path at the beginning, but still has the problem. ~"~

**Comment by diegoceccarelli** [comment]
feel free to contact me on skype, and we can troubleshot the problem
together :) diego.ceccarelli

**Comment by TroisLiu** [comment]
Ok, I will contact you.  Thanks your help  : )

I think maybe I should write down the steps what I have done to let you check easily.

Step 1.
1.1 Downloaded the enwiki dump from the wiki dump website:
I download this version "enwiki-20151201-pages-articles.xml.bz2" : https://dumps.wikimedia.org/enwiki/20151201/enwiki-20151201-pages-articles.xml.bz2

1.2 Downloaded the json-wikipedia from @diegoceccarelli 's github 
and follow the tips to generate the jar file : "json-wikipedia-1.0.0-jar-with-dependencies.jar".
Then I use the jar file to convert the enwiki-dump to the json file :  "enwiki-latest-pages-articles.json"

Step 2.
2.0 Downloaded the dexter-master from this github
and generate the jarfile : "dexter-core-2.1.0-jar-with-dependencies.jar"

2.1. Change the values of variable in delowdexter-core\scripts\config.sh  :
line 3 : VERSION = "2.1.0"
line 23 : DATA_DIR = en-model-20151201
line 34 : WIKI_JSON_DUMP= enwiki-latest-pages-articles.json

2.2 Then set the path in the  dexter-conf.xml 
line 8 :  <path>en-model-20151201</path>

Step 3. run the scripts\create-label2id-file.sh
It generated the en-model-20151201 folder, which contain 2 folders and 1 file: 
   tmp folder  : which is empty folder
   mapdb folder : contain 2 files : mapdb.db (65KB) & mapdb.db.p(13KB) 
   title-redirect-id.tsv file : which size is 0

Step 4.  run scripts\index-dump-with-lucene.sh 
This step create the en-model-20151201\lucene folder and lots of files

Step 5. run scripts\generate-spots.sh
Exception happened in this step @~@
java.io.IOException: storage has invalid header (The screenshot is the above comment )

**Comment by brunoalano** [comment]
I have the same issue of @tgalery, giving me:
`2015-08-13 21:23:49,738 51545 [main] INFO  it.cnr.isti.hpc.dexter.cli.spot.ExtractSpotsCLI - cannot find id for label Jo?o_Carlos_Batista`

I've checked the `wikipedia json dump` and the ` label2id file`, and they are correct. The accents are displayed correctly.

**Comment by diegoceccarelli** [comment]
@brunoalano are you sure that the particular label in the article is not misspelled? since wikinames are manually added by the editors sometimes they copy and paste from other editors using different encodings. could you try to  use the api and search for the wikiname?

**Comment by liute110** [comment]
hi,when I run scripts\generate-spots.sh. but it show that " can not find for **".I want to genarat data model which support chinese.

**Comment by liute110** [comment]
hi ,I want to build data model for chinese. I didn't get right result .I think I have made some mistake.But   I have run every steps  and succed.
![default](https://cloud.githubusercontent.com/assets/19482770/15846106/7f31a2dc-2cac-11e6-850a-70d814c4a8f8.png)

**Comment by lx865712528** [comment]
@TroisLiu I met this problem just now and the problem has gone after I upgrade mapdb in pom.xml to 1.0.8 later...

**Comment by lx865712528** [comment]
* Maybe adding the line `mkdir -p $GRAPH_DIR` in `generate-incoming-and-outcoming-edges.sh` is necessary when meeting problem like `no such file`.
* Maybe replacing the line [https://github.com/dexter/dexter/blob/master/dexter-core/scripts/generate-succint-spot-index.sh#L8][1] with `gzcat $SPOT_FILE > $TTMP` is better.

[1]: https://github.com/dexter/dexter/blob/master/dexter-core/scripts/generate-succint-spot-index.sh#L8

**Comment by mohammadalijf** [comment]
i am trying to build a english model for 23-Jun-2018. when i ran create-label2id-file.sh script i get following error: i think it's some kind of a overflow problem.

> 2018-06-27 00:02:32,696 401  [main] INFO  it.cnr.isti.hpc.mapdb.MapDB - get collection a2id
> Exception in thread "main" java.lang.RuntimeException: Writer thread failed
> 	at org.mapdb.AsyncWriteEngine.checkState(AsyncWriteEngine.java:260)
> 	at org.mapdb.AsyncWriteEngine.update(AsyncWriteEngine.java:351)
> 	at org.mapdb.Caches$HashTable.update(Caches.java:233)
> 	at org.mapdb.EngineWrapper.update(EngineWrapper.java:57)
> 	at org.mapdb.SnapshotEngine.update(SnapshotEngine.java:86)
> 	at org.mapdb.BTreeMap.put2(BTreeMap.java:627)
> 	at org.mapdb.BTreeMap.put(BTreeMap.java:561)
> 	at it.cnr.isti.hpc.dexter.label.mapdb.MapDBLabelToId.add(MapDBLabelToId.java:68)
> 	at it.cnr.isti.hpc.dexter.cli.label.IndexLabelToIdCLI.store(IndexLabelToIdCLI.java:70)
> 	at it.cnr.isti.hpc.dexter.cli.label.IndexLabelToIdCLI.main(IndexLabelToIdCLI.java:62)
> Caused by: java.io.IOError: java.io.EOFException: offset: 121389237360496
> 	at org.mapdb.Volume$ByteBufferVol.internalByteBuffer(Volume.java:317)
> 	at org.mapdb.Volume$ByteBufferVol.putData(Volume.java:339)
> 	at org.mapdb.StoreDirect.put2(StoreDirect.java:257)
> 	at org.mapdb.StoreDirect.update2(StoreDirect.java:394)
> 	at org.mapdb.StoreDirect.update(StoreDirect.java:350)
> 	at org.mapdb.EngineWrapper.update(EngineWrapper.java:57)
> 	at org.mapdb.AsyncWriteEngine.access$101(AsyncWriteEngine.java:69)
> 	at org.mapdb.AsyncWriteEngine.runWriter(AsyncWriteEngine.java:202)
> 	at org.mapdb.AsyncWriteEngine$WriterRunnable.run(AsyncWriteEngine.java:152)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.io.EOFException: offset: 121389237360496
> 	... 10 more
> Exception in thread "MapDB shutdown" java.lang.RuntimeException: Writer thread failed
> 	at org.mapdb.AsyncWriteEngine.checkState(AsyncWriteEngine.java:260)
> 	at org.mapdb.AsyncWriteEngine.close(AsyncWriteEngine.java:405)
> 	at org.mapdb.EngineWrapper.close(EngineWrapper.java:75)
> 	at org.mapdb.Caches$HashTable.close(Caches.java:289)
> 	at org.mapdb.EngineWrapper.close(EngineWrapper.java:75)
> 	at org.mapdb.DBMaker$1.run(DBMaker.java:710)
> Caused by: java.io.IOError: java.io.EOFException: offset: 121389237360496
> 	at org.mapdb.Volume$ByteBufferVol.internalByteBuffer(Volume.java:317)
> 	at org.mapdb.Volume$ByteBufferVol.putData(Volume.java:339)
> 	at org.mapdb.StoreDirect.put2(StoreDirect.java:257)
> 	at org.mapdb.StoreDirect.update2(StoreDirect.java:394)
> 	at org.mapdb.StoreDirect.update(StoreDirect.java:350)
> 	at org.mapdb.EngineWrapper.update(EngineWrapper.java:57)
> 	at org.mapdb.AsyncWriteEngine.access$101(AsyncWriteEngine.java:69)
> 	at org.mapdb.AsyncWriteEngine.runWriter(AsyncWriteEngine.java:202)
> 	at org.mapdb.AsyncWriteEngine$WriterRunnable.run(AsyncWriteEngine.java:152)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.io.EOFException: offset: 121389237360496
> 	... 10 more

also if you know any link to a updated model for dexter it would be nice

**Comment by vwoloszyn** [comment]
Hi guys would be possible to provide a link to an updated model (the current is based on Wikipedia dump of 2014)? It would be extremally useful :)

**Comment by mohammadalijf** [comment]
@vwoloszyn hi, 
i've mannaged to create a wikipedia model for latest dump but it is 60.18 GB which i can not upload anywhere. i would be happy to guide you through the process though.

**Comment by vwoloszyn** [comment]
Hi Mohammad, many thanks for the answer.
Why do not make it available (compressed) at a Dexter website as an
'optional' download? I guess several dudes are having the same problem :)

Anyway, would be very nice if you could guide me through the process.

Best,
Vinicius

**Comment by diegoceccarelli** [comment]
Hi, I'm the main developer of Dexter. I'm working on a new version that unfortunately.will not be compatible with the old model. I don't have time to generate new model but I would be happy to host a new model if you can provide it. If you want to try the new Dexter I can provide a fresher model.

Let me know.
Diego

**Comment by vwoloszyn** [comment]
Great! @mohammadalijf would be possible to you share your model? @diegoceccarelli can host it and make it available for the Dexter community.

**Comment by mohammadalijf** [comment]
@vwoloszyn @diegoceccarelli 
sorry for delay. i've got a real slow connection so i don't know if i can upload the model but i can try if @diegoceccarelli provides me a host for uploading.

**Comment by vwoloszyn** [comment]
Great! @diegoceccarelli Would be possible for you to provide the host to upload the model? 
Best,
Vinicius

**Comment by diegoceccarelli** [comment]
Hey guys, would you like to organize a Skype call? Would be nice to have a
chat

**Comment by vwoloszyn** [comment]
@diegoceccarelli @mohammadalijf  Sure! My skype is vinicius.woloszyn

**Comment by rahuldeve** [comment]
@vwoloszyn Hi, Ive just finished building a model based on the latest English wikipedia dump. Do let me know if you want it. I can try making it available online.

**Comment by diegoceccarelli** [comment]
Guys, would you like to have a Skype call? I can in the evening (GMT+1) and
during the weekends. What about this Sunday at around 18.00 GMT+1?

**Comment by vwoloszyn** [comment]
Thank you @rahuldeve . Are you available to make a skype this Sunday, as @diegoceccarelli suggested? 

Best,

**Comment by rahuldeve** [comment]
@diegoceccarelli @vwoloszyn Unfortunately I wont be available this Sunday. I am kind of packed this month but I am more than happy to discuss here.

**Comment by diegoceccarelli** [comment]
Alright, Raul are you able to host the data?

Vinicius we might have the call anyway if you like :)

**Comment by rahuldeve** [comment]
@diegoceccarelli  Yes. Its in Amazon S3 for now. I will try moving it to my Google Drive account first. The trained model folder along with the Lucene indexes comes around 35GB compressed. The one without the indexes is around 3.4GB. Which one should I make available ?

**Comment by vwoloszyn** [comment]
@diegoceccarelli  Yes, I am free to talk :)

**Comment by diegoceccarelli** [comment]
Raul, I would make available the 3.5Gb, the other would take ages to
upload/download :) if you want to submit a PR with the address of the repo
in the readme I would merge it.

**Comment by rahuldeve** [comment]
@vwoloszyn @diegoceccarelli Sorry for the late reply. I will do that. For now I have uploaded the model in gdrive. Let me know if it works fine from your side too.

https://drive.google.com/open?id=1XwHGoEMwjRLEPQj_D7Mi1osHFoDVHYLD

**Comment by diegoceccarelli** [comment]
@vwoloszyn <https://github.com/vwoloszyn> I'm online on Skype:
diego.ceccarelli :)
