### ISSUE TITLE
Exception on generate one spot per line step

### ISSUE THREAD

**Issue by grivescorbett** [dexter/dexter#19]
I'm trying to build a model from the most recent wikipedia dump, getting an error during generate-one-spot-per-line.sh:

	ubuntu@ip-172-31-5-17:~/dexter/dexter-core$ ./scripts/generate-one-spot-per-line.sh &
	[1] 17148
	ubuntu@ip-172-31-5-17:~/dexter/dexter-core$ merging data/spot/spot-src-target.tsv and data/spot/spots-doc-freq.tsv in data/spot/spots.tsv.gz
	2016-04-22 15:03:53,216 244  [main] INFO  it.cnr.isti.hpc.dexter.cli.spot.WriteOneSpotPerLineCLI - writing spots in data/spot/spots.tsv.gz
	2016-04-22 15:03:53,232 260  [main] INFO  it.cnr.isti.hpc.dexter.util.DexterParams - loading configuration from dexter-conf.xml
	2016-04-22 15:03:53,234 262  [main] INFO  it.cnr.isti.hpc.dexter.util.DexterParamsXMLParser - loading configuration from dexter-conf.xml
	2016-04-22 15:03:53,338 366  [main] INFO  it.cnr.isti.hpc.dexter.plugin.PluginLoader - weka-wrapper-1.0.jar loaded
	2016-04-22 15:03:53,338 366  [main] INFO  it.cnr.isti.hpc.dexter.plugin.PluginLoader - dexter-spotters-2.0.0.jar loaded
	2016-04-22 15:03:53,338 366  [main] INFO  it.cnr.isti.hpc.dexter.plugin.PluginLoader - weka-1.0.jar loaded
	2016-04-22 15:03:53,338 366  [main] INFO  it.cnr.isti.hpc.dexter.util.DexterParams - registering graph entity-entity in: incoming-edges.bin
	2016-04-22 15:03:53,339 367  [main] INFO  it.cnr.isti.hpc.dexter.util.DexterParams - registering graph entity-entity out: outcoming-edges.bin
	2016-04-22 15:03:53,339 367  [main] INFO  it.cnr.isti.hpc.dexter.util.DexterParams - registering graph entity-category in: incoming-entity-category-edges.bin
	2016-04-22 15:03:53,339 367  [main] INFO  it.cnr.isti.hpc.dexter.util.DexterParams - registering graph entity-category out: outcoming-entity-category-edges.bin
	2016-04-22 15:03:53,339 367  [main] INFO  it.cnr.isti.hpc.dexter.util.DexterParams - registering graph category-category in: incoming-category-edges.bin
	2016-04-22 15:03:53,339 367  [main] INFO  it.cnr.isti.hpc.dexter.util.DexterParams - registering graph category-category out: outcoming-category-edges.bin
	2016-04-22 15:03:53,339 367  [main] INFO  it.cnr.isti.hpc.dexter.util.DexterParams - registering disambiguator okkam -> it.cnr.isti.hpc.dexter.disambiguation.TopScoreEntityDisambiguator

	2016-04-22 15:03:53,339 367  [main] INFO  it.cnr.isti.hpc.dexter.util.DexterParams - registering disambiguator tagme -> it.cnr.isti.hpc.tagme.Tagme
	2016-04-22 15:03:53,339 367  [main] INFO  it.cnr.isti.hpc.dexter.util.DexterParams - registering relatedness milnewitten -> it.cnr.isti.hpc.dexter.relatedness.MilneRelatedness
	2016-04-22 15:03:53,339 367  [main] INFO  it.cnr.isti.hpc.dexter.util.DexterParams - registering spot filter probability-filter -> it.cnr.isti.hpc.dexter.spotter.filter.SpotProbabilityFilter
	2016-04-22 15:03:53,339 367  [main] INFO  it.cnr.isti.hpc.dexter.util.DexterParams - registering spot filter overlaps-filter -> it.cnr.isti.hpc.dexter.spotter.filter.SpotOverlapFilter
	2016-04-22 15:03:53,339 367  [main] INFO  it.cnr.isti.hpc.dexter.util.DexterParams - registering spotter wiki-dictionary -> it.cnr.isti.hpc.dexter.spotter.DictionarySpotter
	2016-04-22 15:04:04,864 11892 [main] INFO  it.cnr.isti.hpc.log.ProgressLogger - processed 100000 distinct spots
	2016-04-22 15:04:15,805 22833 [main] INFO  it.cnr.isti.hpc.log.ProgressLogger - processed 200000 distinct spots
    ......
	2016-04-22 15:48:42,993 2690021 [main] INFO  it.cnr.isti.hpc.log.ProgressLogger - processed 11400000 distinct spots
	2016-04-22 15:49:04,850 2711878 [main] INFO  it.cnr.isti.hpc.log.ProgressLogger - processed 11500000 distinct spots
	2016-04-22 15:49:40,511 2747539 [main] INFO  it.cnr.isti.hpc.log.ProgressLogger - processed 11600000 distinct spots
	2016-04-22 15:50:01,791 2768819 [main] WARN  it.cnr.isti.hpc.io.reader.RecordReader - Skipping invalid query result (java.util.NoSuchElementException)
	2016-04-22 15:50:01,791 2768819 [main] ERROR it.cnr.isti.hpc.io.reader.RecordReader - vice admiral charles george edward p
	Exception in thread "main" java.lang.NullPointerException
		at it.cnr.isti.hpc.dexter.spot.SpotReader.generateSpot(SpotReader.java:121)
		at it.cnr.isti.hpc.dexter.spot.SpotReader.getNextSpot(SpotReader.java:99)
		at it.cnr.isti.hpc.dexter.spot.SpotReader.next(SpotReader.java:174)
		at it.cnr.isti.hpc.dexter.cli.spot.WriteOneSpotPerLineCLI.main(WriteOneSpotPerLineCLI.java:78)
	results in data/spot/spots.tsv.gz

Any thoughts would be appreciated.

**Comment by diegoceccarelli** [comment]
Can you give me more context? which dump were you processing? are you using a *pages.articles.xml.gz dump? can you check if the *json dump is malformed?
