### ISSUE TITLE
Page Not Found when following steps

### ISSUE THREAD

**Issue by taha-y-merghani** [dexter/dexter#34]
Hi,

I followed the following steps

> wget http://hpc.isti.cnr.it/~ceccarelli/dexter2.tar.gz
> tar -xvzf dexter2.tar.gz
> cd dexter2
> java -Xmx4000m -jar dexter-2.1.0.jar

Here is a dump from the terminal 
```
NFO: Scanning for root resource and provider classes in the packages:
  it.cnr.isti.hpc.dexter.rest
  com.wordnik.swagger.jersey.listing
Oct 26, 2017 1:27:19 PM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Root resource classes found:
  class it.cnr.isti.hpc.dexter.rest.RestService
  class it.cnr.isti.hpc.dexter.rest.GraphRestService
  class com.wordnik.swagger.jersey.listing.ApiListingResourceJSON
  class it.cnr.isti.hpc.dexter.rest.JSONPService
Oct 26, 2017 1:27:19 PM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Provider classes found:
  class com.wordnik.swagger.jersey.listing.JerseyResourceListingProvider
  class com.wordnik.swagger.jersey.listing.JerseyApiDeclarationProvider
Oct 26, 2017 1:27:19 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.12 02/15/2012 05:30 PM'
2017-10-26 13:27:19,844 23857 [main] WARN  org.eclipse.jetty.util.log - FAILED Jersey Web Application: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
2017-10-26 13:27:20,058 24071 [main] WARN  org.eclipse.jetty.util.log - FAILED o.e.j.w.WebAppContext{/dexter-webapp,file:/Users/tahamerghani/GT-Fall2017/DILAC/dexter2/work/webapp/},file:/Users/tahamerghani/GT-Fall2017/DILAC/dexter2/dexter-2.1.0.jar: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
2017-10-26 13:27:20,058 24071 [main] WARN  org.eclipse.jetty.util.log - FAILED org.eclipse.jetty.server.handler.HandlerList@2e27d72f: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
2017-10-26 13:27:20,066 24079 [main] WARN  org.eclipse.jetty.util.log - Error starting handlers
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.sun.jersey.server.impl.wadl.WadlFactory.init(WadlFactory.java:96) ~[dexter-2.1.0.jar:na]
	at com.sun.jersey.server.impl.application.RootResourceUriRules.initWadl(RootResourceUriRules.java:169) ~[dexter-2.1.0.jar:na]
	at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUriRules.java:106) ~[dexter-2.1.0.jar:na]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicationImpl.java:1308) ~[dexter-2.1.0.jar:na]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicationImpl.java:171) ~[dexter-2.1.0.jar:na]
	at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:777) ~[dexter-2.1.0.jar:na]
	at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:773) ~[dexter-2.1.0.jar:na]
	at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193) ~[dexter-2.1.0.jar:na]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:773) ~[dexter-2.1.0.jar:na]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:768) ~[dexter-2.1.0.jar:na]
	at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:488) ~[dexter-2.1.0.jar:na]
	at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:318) ~[dexter-2.1.0.jar:na]
	at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:607) ~[dexter-2.1.0.jar:na]
	at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:208) ~[dexter-2.1.0.jar:na]
	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:373) ~[dexter-2.1.0.jar:na]
	at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:556) ~[dexter-2.1.0.jar:na]
	at javax.servlet.GenericServlet.init(GenericServlet.java:241) ~[dexter-2.1.0.jar:na]
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:432) ~[dexter-2.1.0.jar:na]
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:260) ~[dexter-2.1.0.jar:na]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55) [dexter-2.1.0.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:762) ~[dexter-2.1.0.jar:na]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:244) ~[dexter-2.1.0.jar:na]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1181) ~[dexter-2.1.0.jar:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:584) ~[dexter-2.1.0.jar:na]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:496) ~[dexter-2.1.0.jar:na]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55) [dexter-2.1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:226) ~[dexter-2.1.0.jar:na]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55) [dexter-2.1.0.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:93) ~[dexter-2.1.0.jar:na]
	at org.eclipse.jetty.server.Server.doStart(Server.java:243) ~[dexter-2.1.0.jar:na]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55) [dexter-2.1.0.jar:na]
	at bekkopen.jetty.Main.start(Main.java:102) [dexter-2.1.0.jar:na]
	at bekkopen.jetty.Main.main(Main.java:27) [dexter-2.1.0.jar:na]
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[na:na]
	... 33 common frames omitted
2017-10-26 13:27:20,094 24107 [main] INFO  org.eclipse.jetty.util.log - Started SelectChannelConnector@0.0.0.0:
```
Then went to the link provided  http://localhost:8080/dexter-webapp/dev, but received a 404 Error Message. 

How can I proceed?

**Comment by danduma** [comment]
I have the same issue!

java 9
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)

2017-11-16 17:22:15,609 4506 [main] INFO  org.eclipse.jetty.util.log - jetty-7.x.y-SNAPSHOT
2017-11-16 17:22:15,630 4527 [main] INFO  org.eclipse.jetty.util.log - Extract jar:file:/Users/dumadan/nlp/dexter2/dexter-2.1.0.jar!/ to /Users/dumadan/nlp/dexter2/work/webapp
Nov 16, 2017 5:22:24 PM com.sun.jersey.api.core.PackagesResourceConfig init
INFO: Scanning for root resource and provider classes in the packages:
  it.cnr.isti.hpc.dexter.rest
  com.wordnik.swagger.jersey.listing
Nov 16, 2017 5:22:27 PM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Root resource classes found:
  class it.cnr.isti.hpc.dexter.rest.GraphRestService
  class it.cnr.isti.hpc.dexter.rest.JSONPService
  class it.cnr.isti.hpc.dexter.rest.RestService
  class com.wordnik.swagger.jersey.listing.ApiListingResourceJSON
Nov 16, 2017 5:22:27 PM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Provider classes found:
  class com.wordnik.swagger.jersey.listing.JerseyApiDeclarationProvider
  class com.wordnik.swagger.jersey.listing.JerseyResourceListingProvider
Nov 16, 2017 5:22:27 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.12 02/15/2012 05:30 PM'
2017-11-16 17:22:28,173 17070 [main] WARN  org.eclipse.jetty.util.log - FAILED Jersey Web Application: java.lang.NoClassDefFoundError: javax/xml/ind/JAXBException
2017-11-16 17:22:28,285 17182 [main] WARN  org.eclipse.jetty.util.log - FAILED o.e.j.w.WebAppContext{/dexter-webapp,file:/Users/dumadan/nlp/dexter2/work/webapp/},file:/Users/dumadan/nlp/dexter2/dexter-2.1.0.jar: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
2017-11-16 17:22:28,285 17182 [main] WARN  org.eclipse.jetty.util.log - FAILED org.eclipse.jetty.server.handler.HandlerList@1f2d2181: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
2017-11-16 17:22:28,288 17185 [main] WARN  org.eclipse.jetty.util.log - Error starting handlers
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
at com.sun.jersey.server.impl.wadl.WadlFactory.init(WadlFactory.java:96) ~[dexter-2.1.0.jar:na]
at com.sun.jersey.server.impl.application.RootResourceUriRules.initWadl(RootResourceUriRules.java:169) ~[dexter-2.1.0.jar:na]
at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUriRules.java:106) ~[dexter-2.1.0.jar:na]
at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicationImpl.java:1308) ~[dexter-2.1.0.jar:na]
at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicationImpl.java:171) ~[dexter-2.1.0.jar:na]
at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:777) ~[dexter-2.1.0.jar:na]
at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:773) ~[dexter-2.1.0.jar:na]
at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193) ~[dexter-2.1.0.jar:na]
at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:773) ~[dexter-2.1.0.jar:na]
at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:768) ~[dexter-2.1.0.jar:na]
at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:488) ~[dexter-2.1.0.jar:na]
at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:318) ~[dexter-2.1.0.jar:na]
at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:607) ~[dexter-2.1.0.jar:na]
at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:208) ~[dexter-2.1.0.jar:na]
at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:373) ~[dexter-2.1.0.jar:na]
at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:556) ~[dexter-2.1.0.jar:na]
at javax.servlet.GenericServlet.init(GenericServlet.java:241) ~[dexter-2.1.0.jar:na]
at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:432) ~[dexter-2.1.0.jar:na]
at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:260) ~[dexter-2.1.0.jar:na]
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55) [dexter-2.1.0.jar:na]
at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:762) ~[dexter-2.1.0.jar:na]
at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:244) ~[dexter-2.1.0.jar:na]
at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1181) ~[dexter-2.1.0.jar:na]
at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:584) ~[dexter-2.1.0.jar:na]
at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:496) ~[dexter-2.1.0.jar:na]
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55) [dexter-2.1.0.jar:na]
at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:226) ~[dexter-2.1.0.jar:na]
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55) [dexter-2.1.0.jar:na]
at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:93) ~[dexter-2.1.0.jar:na]
at org.eclipse.jetty.server.Server.doStart(Server.java:243) ~[dexter-2.1.0.jar:na]
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55) [dexter-2.1.0.jar:na]
at bekkopen.jetty.Main.start(Main.java:102) [dexter-2.1.0.jar:na]
at bekkopen.jetty.Main.main(Main.java:27) [dexter-2.1.0.jar:na]
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582) ~[na:na]
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185) ~[na:na]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[na:na]
... 33 common frames omitted
2017-11-16 17:22:28,304 17201 [main] INFO  org.eclipse.jetty.util.log - Started SelectChannelConnector@0.0.0.0:8080

**Comment by diegoceccarelli** [comment]
what JVM are you using? 

have a look at https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

in alternative, can you try running dexter follow the steps that I wrote in https://github.com/dexter/dexter/issues/32?

**Comment by danduma** [comment]
I'm using the official Oracle Java 9 JVM, as I posted above, and on MacOS Sierra:
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)

Adding --add-modules java.xml.bind to the command line as the stackoverflow article above recommends worked, so it's clearly a Java 9 thing :)

Apparently the order of parameters matters, so:

java -Xmx3000m --add-modules java.xml.bind -jar dexter-2.1.0.jar

As a side note, I tried mvn compile inside dexter-webapp as you recommend in #32 , and this happened:

[ERROR] Failed to execute goal on project dexter-webapp: Could not resolve dependencies for project it.cnr.isti.hpc:dexter-webapp:jar:2.1.0: The following artifacts could not be resolved: it.cnr.isti.hpc:dexter-core:jar:2.1.0, it.cnr.isti.hpc:dexter-tagme:jar:2.1.0, it.cnr.isti.hpc:dexter-wikiminer:jar:2.0.0, it.cnr.isti.hpc:json-wikipedia:jar:1.0.0, it.cnr.isti.hpc:dexter-common:jar:0.0.1-SNAPSHOT, simplenlg:simplenlg:jar:4.4: Could not find artifact it.cnr.isti.hpc:dexter-core:jar:2.1.0 in diego's dropbox (https://dl.dropboxusercontent.com/u/4663256/mvn-repository/)

**Comment by danduma** [comment]
Now loading http://localhost:8080/dexter-webapp/dev/

I see the Swagger interface but it only shows this in the content space:

500 : undefined http://localhost:8080/dexter-webapp/api/api-docs/

I post this here as it seems relevant to the error before.
