### ISSUE TITLE
I want to get categories of enties.

### ISSUE THREAD

**Issue by mathematiciseverywhere** [dexter/dexter#39]

**Comment by mathematiciseverywhere** [comment]
hi @diegoceccarelli and @yashmuni. Could you help me.
I want to run         generate-incoming-and-outcoming-category-edges-from-dbpedia.sh 
for getting categories of entities. But in bellow line i get error.
echo "generate edges"
$JAVA $CLI.categories.ExtractDbpediaCategoriesCLI --input $TTMP --output $TTTMP

~/dexter-master/dexter-core$ $JAVA $CLI.categories.ExtractDbpediaCategoriesCLI --input $TTMP --output $TTTMP
2018-05-10 20:57:09,069 117  [main] INFO  it.cnr.isti.hpc.dexter.util.DexterParams - loading configuration from dexter-conf.xml 
2018-05-10 20:57:09,070 118  [main] INFO  it.cnr.isti.hpc.dexter.util.DexterParamsXMLParser - loading configuration from dexter-conf.xml 
**Exception in thread "main" java.lang.ExceptionInInitializerError
	at it.cnr.isti.hpc.dexter.label.mapdb.MapDBIdToLabel.<init>(MapDBIdToLabel.java:51)
	at it.cnr.isti.hpc.dexter.label.mapdb.MapDBIdToLabel.getInstance(MapDBIdToLabel.java:58)
	at it.cnr.isti.hpc.dexter.label.IdHelperFactory.getIdHelper(IdHelperFactory.java:49)
	at it.cnr.isti.hpc.dexter.label.IdHelperFactory.getStdIdHelper(IdHelperFactory.java:109)
	at** it.cnr.isti.hpc.dexter.cli.categories.ExtractDbpediaCategoriesCLI.main(ExtractDbpediaCategoriesCLI.java:57)
**Caused by: com.thoughtworks.xstream.io.StreamException:  : ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.**
	at com.thoughtworks.xstream.io.xml.StaxReader.pullNextEvent(StaxReader.java:53)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:126)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:119)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.move(AbstractPullReader.java:98)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.moveDown(AbstractPullReader.java:83)
	at com.thoughtworks.xstream.io.xml.StaxReader.<init>(StaxReader.java:33)
	at com.thoughtworks.xstream.io.xml.StaxDriver.createStaxReader(StaxDriver.java:115)
	at com.thoughtworks.xstream.io.xml.StaxDriver.createReader(StaxDriver.java:66)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:781)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:773)
	at it.cnr.isti.hpc.dexter.util.DexterParamsXMLParser.load(DexterParamsXMLParser.java:897)
	at it.cnr.isti.hpc.dexter.util.DexterParams.<init>(DexterParams.java:112)
	at it.cnr.isti.hpc.dexter.util.DexterParams.getInstance(DexterParams.java:251)
	at it.cnr.isti.hpc.dexter.label.mapdb.MapDBInstance.<clinit>(MapDBInstance.java:30)
	... 5 more
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:604)
	at com.thoughtworks.xstream.io.xml.StaxReader.pullNextEvent(StaxReader.java:38)
	... 18 more

**Comment by diegoceccarelli** [comment]
@mathematiciseverywhere you need the dexter model to do that. you can generate the model following the steps from the beginning or you can try to download it from the website (there is a zip with all the binary files).

**Comment by mathematiciseverywhere** [comment]
@diegoceccarelli  you mean ı must download ? --->    incoming-entity-category-edges.bin 
                                                                           ---->   outcoming-entity-category-edges.bin
I cannot find any link for model bin files. Where can I download the bin files?
@TroisLiu @yashmuni

**Comment by diegoceccarelli** [comment]
I mean download http://dexter.isti.cnr.it/dexter.tar.gz, get the model directory from there, and then rerun the script to generate the categories.

**Comment by mathematiciseverywhere** [comment]
@diegoceccarelli I got the same error.

uncompressing
extracting entity categories relationships
en-model-20180201/tmp/tmp1
generate edges
2018-05-13 20:49:09,825 114  [main] INFO  it.cnr.isti.hpc.dexter.util.DexterParams - loading configuration from dexter-conf.xml 
2018-05-13 20:49:09,827 116  [main] INFO  it.cnr.isti.hpc.dexter.util.DexterParamsXMLParser - loading configuration from dexter-conf.xml 
Exception in thread "main" java.lang.ExceptionInInitializerError
	at it.cnr.isti.hpc.dexter.label.mapdb.MapDBIdToLabel.<init>(MapDBIdToLabel.java:49)
	at it.cnr.isti.hpc.dexter.label.mapdb.MapDBIdToLabel.getInstance(MapDBIdToLabel.java:56)
	at it.cnr.isti.hpc.dexter.label.IdHelperFactory.getIdHelper(IdHelperFactory.java:49)
	at it.cnr.isti.hpc.dexter.label.IdHelperFactory.getStdIdHelper(IdHelperFactory.java:109)
	at it.cnr.isti.hpc.dexter.cli.categories.ExtractDbpediaCategoriesCLI.main(ExtractDbpediaCategoriesCLI.java:57)
Caused by: com.thoughtworks.xstream.io.StreamException:  : ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
	at com.thoughtworks.xstream.io.xml.StaxReader.pullNextEvent(StaxReader.java:53)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:126)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:119)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.move(AbstractPullReader.java:98)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.moveDown(AbstractPullReader.java:83)
	at com.thoughtworks.xstream.io.xml.StaxReader.<init>(StaxReader.java:33)
	at com.thoughtworks.xstream.io.xml.StaxDriver.createStaxReader(StaxDriver.java:115)
	at com.thoughtworks.xstream.io.xml.StaxDriver.createReader(StaxDriver.java:66)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:781)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:773)
	at it.cnr.isti.hpc.dexter.util.DexterParamsXMLParser.load(DexterParamsXMLParser.java:896)
	at it.cnr.isti.hpc.dexter.util.DexterParams.<init>(DexterParams.java:112)
	at it.cnr.isti.hpc.dexter.util.DexterParams.getInstance(DexterParams.java:250)
	at it.cnr.isti.hpc.dexter.label.mapdb.MapDBInstance.<clinit>(MapDBInstance.java:30)
	... 5 more
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:604)
	at com.thoughtworks.xstream.io.xml.StaxReader.pullNextEvent(StaxReader.java:38)
	... 18 more
generate out entity categories
awk: cannot open en-model-20180201/tmp/tmp2 (No such file or directory)
compressing
generate in entity-categories
sort: cannot read: en-model-20180201/tmp/tmp2: No such file or directory
compressing

**Comment by mathematiciseverywhere** [comment]
I solved that error. It is so simple , I want to cry.
<?xml version="1.0" encoding="UTF-8"?> 
I press the backspace before < sign the it run.
Thank you very much @diegoceccarelli.

Occasionally the XML stream that is returned has a "hidden" character before the first "<".  In this case you will receive the  ParseError at [row,col]:[1,1] Message: Content is not allowed in prolog error message.  In order to move past this hidden character and get to the xml you are trying to parse use the following:

**Comment by mathematiciseverywhere** [comment]
@diegoceccarelli I run generate-incoming-and-outcoming-category-edges-from-dbpedia.sh
and I get incoming-entity-categories.tsv.gz and outcoming-entity-categories.tsv.gz
then I convert files to .bin files
I get incoming-entity-categories.bin and outcoming-entity-categories.bin 
you wrote  
		<graph>
			<name>entity-category</name>
			<incoming>incoming-entity-category-edges.bin</incoming>
			<outcoming>outcoming-entity-category-edges.bin</outcoming>
		</graph>

so ı changed file names then I have 
incoming-entity-category-edges.bin and outcoming-entity-category-edges.bin files
and I run my program to get categories. But I get error 

2018-05-14 12:17:21,795 30656 [qtp1159190947-13] INFO  it.cnr.isti.hpc.dexter.graph.ram.RamNodes - loading en-model-20140707/graph/outcoming-entity-category-edges.bin
 
**2018-05-14 12:17:21,796 30657 [qtp1159190947-13] ERROR it.cnr.isti.hpc.io.Serializer - deserializing object (java.io.StreamCorruptedException: invalid stream header: 090A3339)**

2018-05-14 12:17:21,796 30657 [Thread-0] INFO  org.eclipse.jetty.util.log - Graceful shutdown SelectChannelConnector@0.0.0.0:8080

**Comment by mathematiciseverywhere** [comment]
I misunderstand. I understand now. I get prepared model from dexter en-model-20140707 file. 
I download yours dexter code form https://github.com/dexter/dexter .
1 step: I run generate-incoming-and-outcoming-entity-category-edges-from-dbpedia.sh
2.step: scripts/index-incoming-and-outcoming-edges.sh will index the edges in a binary format 
https://github.com/dexter/dexter/blob/master/dexter-core/doc/steps-to-use-dexter.txt ---- line 10
3. I put outcoming-entity-category-edges.bin in dexter en-model-20140707 
It run :) 
Thank you @diegoceccarelli I kept you busy. sorry

**Comment by SMinL** [comment]
> I mean download http://dexter.isti.cnr.it/dexter.tar.gz, get the model directory from there, and then rerun the script to generate the categories.

I can not download from the link that you provide, I wonder that if you can help me.
